### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by Navino16** [kabukki/YARVIS#3]
![capture](https://user-images.githubusercontent.com/22234867/29986733-0f405ff0-8f65-11e7-9dcc-b58083be2e78.PNG)
![capture2](https://user-images.githubusercontent.com/22234867/29986774-314ae782-8f65-11e7-86b5-c2d0c9c9f605.PNG)

Lorsque je veux archiver un projet, il apparaît bien en tant qu'archivé mais n'est pas déplacé.

**Comment by kabukki** [comment]
Probablement archives.directory qui est invalide car '/' au lieu de '\\'

**Comment by Navino16** [comment]
Non ca ne viens pas de la

**Comment by kabukki** [comment]
Double \\ (le formatage l'a efface)
